version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/workspace:cached
      - pip-volume:/workspace/vendor
    command: 'uvicorn main:app --reload --host 0.0.0.0'
  db:
      image: mysql:5.7
      container_name: db
      environment:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_DATABASE: sample_db
        MYSQL_USER: mysqluser
        MYSQL_PASSWORD: mysqlpass
      volumes:
        - ./db/data:/var/lib/mysql
        - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
        - ./db/initdb.d:/docker-entrypoint-initdb.d
      ports:
        - 3303:3303
      tty: true
volumes:
  pip-volume:
