version: '3'
services:
  api:                 # `devcontainer.json`の'service'と一致させる
    container_name: 'python'  # コンテナ名
    hostname: 'python'        # ホスト名.ゲストOSのシェルに表示されるので指定している

    # 以下は他のリポジトリも全て同じ設定にしています
    build: .                  # Dockerfileがあるディレクトリ
    restart: always           # 常に再起動
    working_dir: '/workspace' # デフォルトの作業ディレクトリ
    tty: true                 # コンテナを終了させずに待たせる
    volumes:                  # ホストとゲストのディレクトリを紐づける
      - type: bind            # ホストのディレクトリをゲストにマウントさせる
        source: ../workspace  # ホストの`workspace`ディレクトリを指定
        target: /workspace    # ゲストの`/workspace`にマウントさせる